name: Deploy to Beget via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: tehmin52.beget.tech
          username: tehmin52_dep
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /shashlikmarket/
          exclude: |
            **/.git*
            **/.git*/**
            **/venv/**
            **/__pycache__/**
            **/*.pyc
            .env
